### ISSUE TITLE
Texture Loading Issues

### ISSUE THREAD

**Issue by Clashsoft** [MinestrapTeam/Extrapolated-Dimensions#11]
Texture Loading currently seems to be broken for the entire mod and API. After startup, many items do not have textures or are displayed as white boxes. Reloading the Resource Packs seems to resolve this issue.

**Comment by Delocuro** [comment]
Actually, I've found this seems to just be a Minecraft/Forge issue when playing on Mac computers. For whatever reason, you almost always have to re-load your textures to get them to work, or else half of the non-Vanilla items just show up as white boxes with random-colored pixels. Anyways, it happens with Minestrapp 4 in 1.8 too, so I doubt it's an issue caused by either of the mods.
